POST http://localhost:5267/login
Content-Type: application/json

{
    "email": "Boo@gmail.com",
    "password": "Boo@2121"
}

###
GET http://localhost:5267/signin
Content-Type: application/json

{
    "email": "rr@gmail.com",
    "password": "1234"
}

###
GET http://localhost:5267/getmenudata